/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "HashCash"): TruffleContracts.HashCashContract;
      require(name: "IERC1620"): TruffleContracts.IERC1620Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pausable"): TruffleContracts.PausableContract;
      require(name: "PauserRole"): TruffleContracts.PauserRoleContract;
      require(name: "PersonalToken"): TruffleContracts.PersonalTokenContract;
      require(
        name: "ReentrancyGuard"
      ): TruffleContracts.ReentrancyGuardContract;
    }
  }
}
